export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const SPEAK_WORDS = 'SPEAK_WORDS';
export const TOGGLE_CIRCLE_IMAGES = 'TOGGLE_CIRCLE_IMAGES';

export const EXEC_WORD_BEHAVIOR = 'EXEC_WORD_BEHAVIOR';
export const SWITCH_WORD_BEHAVIOR = 'SWITCH_WORD_BEHAVIOR';
export const SWITCH_WORD_BEHAVIOR_SERVICE = 'SWITCH_WORD_BEHAVIOR_SERVICE';
export const UPDATE_WORD_SEARCH_KEYWORD = 'UPDATE_WORD_SEARCH_KEYWORD';
export const SET_SPEECH_SPEED = 'SET_SPEECH_SPEED';

export const CIRCLE_MODE = 'CIRCLE_MODE';

export const START_3D_MODE = 'START_3D_MODE';
export const GO_NEXT_ROOM = 'GO_NEXT_ROOM';
export const GO_INDEX_ROOM = 'GO_INDEX_ROOM';
export const UPDATE_FLOOR_STATUS = 'UPDATE_FLOOR_STATUS';

export const CHANGE_INDEX_SELECTION = 'CHANGE_INDEX_SELECTION';
export const SPEAK_INDEX_WORDS = 'SPEAK_INDEX_WORDS';
export const TOGGLE_SPEAK_ALL_CIRCLES = 'TOGGLE_SPEAK_ALL_CIRCLES';

