export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const SPEAK_WORDS = 'SPEAK_WORDS';

export const EXEC_WORD_BEHAVIOR = 'EXEC_WORD_BEHAVIOR';
export const SWITCH_WORD_BEHAVIOR = 'SWITCH_WORD_BEHAVIOR';
export const UPDATE_WORD_SEARCH_KEYWORD = 'UPDATE_WORD_SEARCH_KEYWORD';

export const STORY_MODE = 'STORY_MODE';
export const CIRCLE_MODE = 'CIRCLE_MODE';
export const STORY_FETCH_SUCCEEDED = 'STORY_FETCH_SUCCEEDED';
export const STORY_INDEX_FETCH_SUCCEEDED = 'STORY_INDEX_FETCH_SUCCEEDED';
export const TOGGLE_STORY_WORDS = 'TOGGLE_STORY_WORDS';

export const START_3D_MODE = 'START_3D_MODE';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'; // deprecated
export const CHANGE_INDEX_FILTER = 'CHANGE_INDEX_FILTER'; // deprecated

export const CHANGE_INDEX_SELECTION = 'CHANGE_INDEX_SELECTION';
export const SPEAK_INDEX_WORDS = 'SPEAK_INDEX_WORDS';
export const TOGGLE_SPEAK_ALL_CIRCLES = 'TOGGLE_SPEAK_ALL_CIRCLES';

export const SPEAK_STORY_WORDS = 'SPEAK_STORY_WORDS';
export const TOGGLE_STORY_INDEX_WORDS = 'TOGGLE_STORY_INDEX_WORDS';
