export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const SPEAK_WORDS = 'SPEAK_WORDS';
export const ACTION_WORD = 'ACTION_WORD';
export const SWITCH_WORD_ACTION = 'SWITCH_WORD_ACTION';
export const UPDATE_WORD_ACTION_KEYWORD = 'UPDATE_WORD_ACTION_KEYWORD';

